name: habiter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_slidable: ^4.0.0
  isar: ^3.0.0-dev.8
  isar_flutter_libs:
    path: packages/isar_flutter_libs
  path_provider: ^2.1.5
  provider: ^6.1.5
  slideable: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.0.0-dev.8
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
