name: habiter
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_slidable: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  slideable: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^5.13.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/habiter-logo.png"

flutter_native_splash:
  color: "#004FC7"       
  image: assets/habiter-logo.png  
  android: true
  ios: true
